DROP TABLE if EXISTS Defeitos
DROP TABLE if EXISTS Maquinas
DROP TABLE if EXISTS Causas
DROP TABLE if EXISTS Solucoes

CREATE TABLE Defeitos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    defeito VARCHAR(1000) NOT NULL
);
CREATE TABLE Maquinas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    maquina VARCHAR(20) NOT NULL
);
CREATE TABLE Causas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    causa VARCHAR(1000) NOT NULL
);
CREATE TABLE Solucoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    solucao VARCHAR(1000) NOT NULL
);